Deobfuscate and fix a bunch of more imports to allow network code to run
Crashes with:
ValueError: moose_element: '/D2[0]/primdend1[0]/spine0head[0]/ampa[0]/SH' does not exist!